### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [AllexxYu/Final#1]
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Comment by AllexxYu** [comment]
не могу получить из v-bootstrap, ошибки. config вот такой
[core]
    repositoryformatversion = 0
    filemode = false
    bare = false
    logallrefupdates = true
    symlinks = false
    ignorecase = true
    quotepath = false
[remote "origin"]
    url = https://github.com/AllexxYu/Final.git
    fetch = +refs/heads/_:refs/remotes/origin/_
[branch "master"]
    remote = origin
    merge = refs/heads/master
[user]
    name = Allexx.Yu
    email = Allexx.Yu@yandex.ru
[remote "vanessa-bootstrap"]
    url = https://github.com/silverbulleters/vanessa-bootstrap.git
    fetch = +refs/heads/_:refs/remotes/vanessa-bootstrap/_
[diff]
    mnemonicprefix = false

**Comment by AllexxYu** [comment]
Внешние отчеты и обработки разбираются на исходники - что имеется в виду? у меня ведь нет ни внешних отчетов ни обработок

**Comment by AllexxYu** [comment]
Ошибку при получении из vanessa - bootstrap победить не удалось. Создала новый public repo на bitbucket  https://allexxyu@bitbucket.org/allexxyu/final_task.git

**Comment by alehinsasha** [comment]
на bitbucket репо не нужно было создавать, остаемся на этом

**Comment by alehinsasha** [comment]
На следующем шаге после написания фичи вы сгенерируете обработку проверки этой фичи. Вот она то и должна разбираться на исходники.

**Comment by alehinsasha** [comment]
Достаточно каталоги в вашем репо создать с такими же именами как каталоги в vanessa-bootstrap.

**Comment by alehinsasha** [comment]
Пишите, если будут вопросы.
