### ISSUE TITLE
Формирование описания разработки

### ISSUE THREAD

**Issue by alehinsasha** [AllexxYu/Final#2]
- [x] Коммиты с доступным описанием
- [x] Коммиты привязаны к issue

**Comment by AllexxYu** [comment]
Александр, что должно быть результатом выполнения данной задачи? Задание на разработку в виде issues или что-то еще?

**Comment by alehinsasha** [comment]
Чтобы закрыть этот issue я хочу увидеть несколько коммитов, привязанных к той или иной issue и с более-менее доступным описанием. Описание должно помогать понять для чего были сделаны изменения, а не что изменилось.
